apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: statuspage
spec:
  title: StatusPage
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAVklEQVR4nO3QwQmAQAxFwRytYwuzSWvYZraJaANCDkJYnAf/nkmEJOlpzDMr677zNYDuPgN0fQIAAAAAYH/Auo6sDAAAAAAAAAAAAAAAAAAAAECS9PNuAXbvWkEW17sAAAAASUVORK5CYII=
  statusInformers:
    - deployment/statuspage
  ports:
    - serviceName: statuspage
      servicePort: 8080
      localPort: 8080
      applicationUrl: "http://statuspage"
