apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 3.0.0-alpha-31+k8s-1.34
  domains:
    proxyRegistryDomain: salah-statuspage.puresoft.app
  extensions:
    helmCharts:
      - chart:
          name: traefik
          chartVersion: "39.0.7"
        releaseName: traefik
        namespace: traefik
        values:
          image:
            registry: 'repl{{ ReplicatedImageRegistry "docker.io" }}'
            repository: 'repl{{ ReplicatedImageRepository "docker.io/library/traefik" }}'
          service:
            type: NodePort
            nodePorts:
              web: 80
              websecure: 443
          certificatesResolvers:
            letsencrypt:
              acme:
                email: 'repl{{ ConfigOption "tls_acme_email" }}'
                tlsChallenge: true
                storage: /data/acme.json
          persistence:
            enabled: true
            size: 128Mi
