{{- if .Values.global }}
{{- if .Values.global.replicated }}
{{- if .Values.global.replicated.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statuspage.fullname" . }}-replicated-pull-secret
  labels:
    {{- include "statuspage.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson }}
{{- end }}
{{- end }}
{{- end }}
