apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statuspage.fullname" . }}-secrets
  labels:
    {{- include "statuspage.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ include "statuspage.dbPassword" . | quote }}
  centrifugo-api-key: {{ include "statuspage.centrifugoAPIKey" . | quote }}
  jwt-secret: {{ .Values.app.jwtSecret | default (randAlphaNum 32) | quote }}
  {{- if .Values.app.resendApiKey }}
  resend-api-key: {{ .Values.app.resendApiKey | quote }}
  {{- end }}
