{{- if and .Values.ingress.enabled .Values.ingress.customTLS }}
{{- if and .Values.ingress.customTLS.cert .Values.ingress.customTLS.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statuspage.fullname" . }}-tls
  labels:
    {{- include "statuspage.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.customTLS.cert }}
  tls.key: {{ .Values.ingress.customTLS.key }}
{{- end }}
{{- end }}
